//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlimeNull.DuckovCoreUtilities.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsText() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlimeNull.DuckovCoreUtilities.Localization.SettingsText", typeof(SettingsText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Opacity while aiming 的本地化字符串。
        /// </summary>
        internal static string AimOpacity {
            get {
                return ResourceManager.GetString("AimOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 gain {0} 的本地化字符串。
        /// </summary>
        internal static string BlackMarketDemandGain {
            get {
                return ResourceManager.GetString("BlackMarketDemandGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 lose {0} 的本地化字符串。
        /// </summary>
        internal static string BlackMarketDemandLoss {
            get {
                return ResourceManager.GetString("BlackMarketDemandLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 same 的本地化字符串。
        /// </summary>
        internal static string BlackMarketSame {
            get {
                return ResourceManager.GetString("BlackMarketSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Same price 的本地化字符串。
        /// </summary>
        internal static string BlackMarketSamePrice {
            get {
                return ResourceManager.GetString("BlackMarketSamePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 costs {0} more 的本地化字符串。
        /// </summary>
        internal static string BlackMarketSupplyMore {
            get {
                return ResourceManager.GetString("BlackMarketSupplyMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 save {0} 的本地化字符串。
        /// </summary>
        internal static string BlackMarketSupplySave {
            get {
                return ResourceManager.GetString("BlackMarketSupplySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} / Total (x{1}): {2} 的本地化字符串。
        /// </summary>
        internal static string BlackMarketTotalFormat {
            get {
                return ResourceManager.GetString("BlackMarketTotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pulse period 的本地化字符串。
        /// </summary>
        internal static string BreathingPeriod {
            get {
                return ResourceManager.GetString("BreathingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seconds required for one outline brightness cycle 的本地化字符串。
        /// </summary>
        internal static string BreathingPeriodTooltip {
            get {
                return ResourceManager.GetString("BreathingPeriodTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Combat and HUD 的本地化字符串。
        /// </summary>
        internal static string CategoryCombatAndHud {
            get {
                return ResourceManager.GetString("CategoryCombatAndHud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Items and economy 的本地化字符串。
        /// </summary>
        internal static string CategoryItemsAndEconomy {
            get {
                return ResourceManager.GetString("CategoryItemsAndEconomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loot and inventory 的本地化字符串。
        /// </summary>
        internal static string CategoryLootAndInventory {
            get {
                return ResourceManager.GetString("CategoryLootAndInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map and time 的本地化字符串。
        /// </summary>
        internal static string CategoryMapAndTime {
            get {
                return ResourceManager.GetString("CategoryMapAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window behavior 的本地化字符串。
        /// </summary>
        internal static string CategoryWindowBehavior {
            get {
                return ResourceManager.GetString("CategoryWindowBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close when hurt 的本地化字符串。
        /// </summary>
        internal static string CloseWhenHurt {
            get {
                return ResourceManager.GetString("CloseWhenHurt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close while moving 的本地化字符串。
        /// </summary>
        internal static string CloseWhileMoving {
            get {
                return ResourceManager.GetString("CloseWhileMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Demand price comparison baseline 的本地化字符串。
        /// </summary>
        internal static string DemandPriceBaseline {
            get {
                return ResourceManager.GetString("DemandPriceBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display duration 的本地化字符串。
        /// </summary>
        internal static string DisplayDuration {
            get {
                return ResourceManager.GetString("DisplayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display style 的本地化字符串。
        /// </summary>
        internal static string DisplayMode {
            get {
                return ResourceManager.GetString("DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display size 的本地化字符串。
        /// </summary>
        internal static string DisplaySize {
            get {
                return ResourceManager.GetString("DisplaySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not close when inventory has multiple pages 的本地化字符串。
        /// </summary>
        internal static string DoNotCloseWhenInventoryHasMultiplePages {
            get {
                return ResourceManager.GetString("DoNotCloseWhenInventoryHasMultiplePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fade duration 的本地化字符串。
        /// </summary>
        internal static string FadeDuration {
            get {
                return ResourceManager.GetString("FadeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Favorite marker color 的本地化字符串。
        /// </summary>
        internal static string FavoriteMarkerColor {
            get {
                return ResourceManager.GetString("FavoriteMarkerColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Favorite marker 的本地化字符串。
        /// </summary>
        internal static string FavoriteMarkerStyle {
            get {
                return ResourceManager.GetString("FavoriteMarkerStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto-close inventory 的本地化字符串。
        /// </summary>
        internal static string FeatureAutoCloseBackpack {
            get {
                return ResourceManager.GetString("FeatureAutoCloseBackpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Black market price comparison 的本地化字符串。
        /// </summary>
        internal static string FeatureBlackMarketPrice {
            get {
                return ResourceManager.GetString("FeatureBlackMarketPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show BOSS locations 的本地化字符串。
        /// </summary>
        internal static string FeatureBossMapMarker {
            get {
                return ResourceManager.GetString("FeatureBossMapMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ammo crosshair color 的本地化字符串。
        /// </summary>
        internal static string FeatureCrosshairColor {
            get {
                return ResourceManager.GetString("FeatureCrosshairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show item prices 的本地化字符串。
        /// </summary>
        internal static string FeatureDisplayPrice {
            get {
                return ResourceManager.GetString("FeatureDisplayPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show item quality 的本地化字符串。
        /// </summary>
        internal static string FeatureDisplayQuality {
            get {
                return ResourceManager.GetString("FeatureDisplayQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fade HUD while aiming 的本地化字符串。
        /// </summary>
        internal static string FeatureFadeHud {
            get {
                return ResourceManager.GetString("FeatureFadeHud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show grenade blast radius 的本地化字符串。
        /// </summary>
        internal static string FeatureGrenadeRadius {
            get {
                return ResourceManager.GetString("FeatureGrenadeRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inventory sort buttons 的本地化字符串。
        /// </summary>
        internal static string FeatureInventorySort {
            get {
                return ResourceManager.GetString("FeatureInventorySort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item search sounds 的本地化字符串。
        /// </summary>
        internal static string FeatureItemSearchSound {
            get {
                return ResourceManager.GetString("FeatureItemSearchSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show item uses 的本地化字符串。
        /// </summary>
        internal static string FeatureItemUsage {
            get {
                return ResourceManager.GetString("FeatureItemUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kill feed 的本地化字符串。
        /// </summary>
        internal static string FeatureKillRecord {
            get {
                return ResourceManager.GetString("FeatureKillRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loot outlines 的本地化字符串。
        /// </summary>
        internal static string FeatureLootOutline {
            get {
                return ResourceManager.GetString("FeatureLootOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low-health screen shadow 的本地化字符串。
        /// </summary>
        internal static string FeatureLowHealthShadow {
            get {
                return ResourceManager.GetString("FeatureLowHealthShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimap 的本地化字符串。
        /// </summary>
        internal static string FeatureMinimap {
            get {
                return ResourceManager.GetString("FeatureMinimap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quest favorites 的本地化字符串。
        /// </summary>
        internal static string FeatureQuestFavorites {
            get {
                return ResourceManager.GetString("FeatureQuestFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show item requirements 的本地化字符串。
        /// </summary>
        internal static string FeatureQuestRequirements {
            get {
                return ResourceManager.GetString("FeatureQuestRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick sleep 的本地化字符串。
        /// </summary>
        internal static string FeatureQuickSleep {
            get {
                return ResourceManager.GetString("FeatureQuickSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Better key &amp; blueprint indicators 的本地化字符串。
        /// </summary>
        internal static string FeatureRecordedItemIndicator {
            get {
                return ResourceManager.GetString("FeatureRecordedItemIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show inventory counts 的本地化字符串。
        /// </summary>
        internal static string FeatureStorageCount {
            get {
                return ResourceManager.GetString("FeatureStorageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When game loses focus 的本地化字符串。
        /// </summary>
        internal static string FeatureUnfocused {
            get {
                return ResourceManager.GetString("FeatureUnfocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty magazine color 的本地化字符串。
        /// </summary>
        internal static string FinalWarningColor {
            get {
                return ResourceManager.GetString("FinalWarningColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crosshair color when the magazine is empty 的本地化字符串。
        /// </summary>
        internal static string FinalWarningColorTooltip {
            get {
                return ResourceManager.GetString("FinalWarningColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fuse progress color 的本地化字符串。
        /// </summary>
        internal static string GrenadeProgressColor {
            get {
                return ResourceManager.GetString("GrenadeProgressColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blast radius color 的本地化字符串。
        /// </summary>
        internal static string GrenadeRadiusColor {
            get {
                return ResourceManager.GetString("GrenadeRadiusColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ground item pulse 的本地化字符串。
        /// </summary>
        internal static string GroundItemBreathing {
            get {
                return ResourceManager.GetString("GroundItemBreathing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Heart 的本地化字符串。
        /// </summary>
        internal static string Heart {
            get {
                return ResourceManager.GetString("Heart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide looted lootboxes 的本地化字符串。
        /// </summary>
        internal static string HideLootedLootboxes {
            get {
                return ResourceManager.GetString("HideLootedLootboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hour 的本地化字符串。
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include buildings 的本地化字符串。
        /// </summary>
        internal static string IncludeBuildingRequirements {
            get {
                return ResourceManager.GetString("IncludeBuildingRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include perks 的本地化字符串。
        /// </summary>
        internal static string IncludePerkRequirements {
            get {
                return ResourceManager.GetString("IncludePerkRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include quests 的本地化字符串。
        /// </summary>
        internal static string IncludeQuestRequirements {
            get {
                return ResourceManager.GetString("IncludeQuestRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicator background color 的本地化字符串。
        /// </summary>
        internal static string IndicatorBackgroundColor {
            get {
                return ResourceManager.GetString("IndicatorBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicator text color 的本地化字符串。
        /// </summary>
        internal static string IndicatorTextColor {
            get {
                return ResourceManager.GetString("IndicatorTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initial warning color 的本地化字符串。
        /// </summary>
        internal static string InitialWarningColor {
            get {
                return ResourceManager.GetString("InitialWarningColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crosshair color when first entering the low-ammo range 的本地化字符串。
        /// </summary>
        internal static string InitialWarningColorTooltip {
            get {
                return ResourceManager.GetString("InitialWarningColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item base price 的本地化字符串。
        /// </summary>
        internal static string ItemBasePrice {
            get {
                return ResourceManager.GetString("ItemBasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uses 的本地化字符串。
        /// </summary>
        internal static string ItemUsageAvailable {
            get {
                return ResourceManager.GetString("ItemUsageAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Killed {0} 的本地化字符串。
        /// </summary>
        internal static string KillRecordDefaultFormat {
            get {
                return ResourceManager.GetString("KillRecordDefaultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local audio file 的本地化字符串。
        /// </summary>
        internal static string LocalSoundFile {
            get {
                return ResourceManager.GetString("LocalSoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loot container pulse 的本地化字符串。
        /// </summary>
        internal static string LootboxBreathing {
            get {
                return ResourceManager.GetString("LootboxBreathing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixed angle 的本地化字符串。
        /// </summary>
        internal static string MapFixedAngle {
            get {
                return ResourceManager.GetString("MapFixedAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow player rotation 的本地化字符串。
        /// </summary>
        internal static string MapFollowPlayer {
            get {
                return ResourceManager.GetString("MapFollowPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map orientation 的本地化字符串。
        /// </summary>
        internal static string MapOrientation {
            get {
                return ResourceManager.GetString("MapOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marker color 的本地化字符串。
        /// </summary>
        internal static string MarkerColor {
            get {
                return ResourceManager.GetString("MarkerColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full effect below 的本地化字符串。
        /// </summary>
        internal static string MaximumEffectThreshold {
            get {
                return ResourceManager.GetString("MaximumEffectThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum entries 的本地化字符串。
        /// </summary>
        internal static string MaximumEntries {
            get {
                return ResourceManager.GetString("MaximumEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant buyback price 的本地化字符串。
        /// </summary>
        internal static string MerchantSellback {
            get {
                return ResourceManager.GetString("MerchantSellback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum opacity 的本地化字符串。
        /// </summary>
        internal static string MinimumOpacity {
            get {
                return ResourceManager.GetString("MinimumOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minute 的本地化字符串。
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mute while unfocused 的本地化字符串。
        /// </summary>
        internal static string MuteWhenUnfocused {
            get {
                return ResourceManager.GetString("MuteWhenUnfocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opacity 的本地化字符串。
        /// </summary>
        internal static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause while unfocused 的本地化字符串。
        /// </summary>
        internal static string PauseWhenUnfocused {
            get {
                return ResourceManager.GetString("PauseWhenUnfocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position mode 的本地化字符串。
        /// </summary>
        internal static string PositionMode {
            get {
                return ResourceManager.GetString("PositionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preset time button 1 的本地化字符串。
        /// </summary>
        internal static string PresetTime1 {
            get {
                return ResourceManager.GetString("PresetTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preset time button 2 的本地化字符串。
        /// </summary>
        internal static string PresetTime2 {
            get {
                return ResourceManager.GetString("PresetTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base price 的本地化字符串。
        /// </summary>
        internal static string PriceBase {
            get {
                return ResourceManager.GetString("PriceBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sell price 的本地化字符串。
        /// </summary>
        internal static string PriceSell {
            get {
                return ResourceManager.GetString("PriceSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price type 的本地化字符串。
        /// </summary>
        internal static string PriceType {
            get {
                return ResourceManager.GetString("PriceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 0 的本地化字符串。
        /// </summary>
        internal static string Quality0 {
            get {
                return ResourceManager.GetString("Quality0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 0 color 的本地化字符串。
        /// </summary>
        internal static string Quality0Color {
            get {
                return ResourceManager.GetString("Quality0Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 1 的本地化字符串。
        /// </summary>
        internal static string Quality1 {
            get {
                return ResourceManager.GetString("Quality1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 1 color 的本地化字符串。
        /// </summary>
        internal static string Quality1Color {
            get {
                return ResourceManager.GetString("Quality1Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 2 的本地化字符串。
        /// </summary>
        internal static string Quality2 {
            get {
                return ResourceManager.GetString("Quality2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 2 color 的本地化字符串。
        /// </summary>
        internal static string Quality2Color {
            get {
                return ResourceManager.GetString("Quality2Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 3 的本地化字符串。
        /// </summary>
        internal static string Quality3 {
            get {
                return ResourceManager.GetString("Quality3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 3 color 的本地化字符串。
        /// </summary>
        internal static string Quality3Color {
            get {
                return ResourceManager.GetString("Quality3Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 4 的本地化字符串。
        /// </summary>
        internal static string Quality4 {
            get {
                return ResourceManager.GetString("Quality4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 4 color 的本地化字符串。
        /// </summary>
        internal static string Quality4Color {
            get {
                return ResourceManager.GetString("Quality4Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 5 的本地化字符串。
        /// </summary>
        internal static string Quality5 {
            get {
                return ResourceManager.GetString("Quality5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 5 color 的本地化字符串。
        /// </summary>
        internal static string Quality5Color {
            get {
                return ResourceManager.GetString("Quality5Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 6 的本地化字符串。
        /// </summary>
        internal static string Quality6 {
            get {
                return ResourceManager.GetString("Quality6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 6 color 的本地化字符串。
        /// </summary>
        internal static string Quality6Color {
            get {
                return ResourceManager.GetString("Quality6Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background 的本地化字符串。
        /// </summary>
        internal static string QualityBackground {
            get {
                return ResourceManager.GetString("QualityBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Border 的本地化字符串。
        /// </summary>
        internal static string QualityBorder {
            get {
                return ResourceManager.GetString("QualityBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Corner badge 的本地化字符串。
        /// </summary>
        internal static string QualityCornerBadge {
            get {
                return ResourceManager.GetString("QualityCornerBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press ESC to cancel 的本地化字符串。
        /// </summary>
        internal static string QuickSleepCancelHint {
            get {
                return ResourceManager.GetString("QuickSleepCancelHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancelled searching for a rainy day 的本地化字符串。
        /// </summary>
        internal static string QuickSleepCancelled {
            get {
                return ResourceManager.GetString("QuickSleepCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No rainy day found after {0} day(s) 的本地化字符串。
        /// </summary>
        internal static string QuickSleepExhausted {
            get {
                return ResourceManager.GetString("QuickSleepExhausted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is finally raining after {0} day(s)! 的本地化字符串。
        /// </summary>
        internal static string QuickSleepFound {
            get {
                return ResourceManager.GetString("QuickSleepFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Storm End 的本地化字符串。
        /// </summary>
        internal static string QuickSleepStormEnd {
            get {
                return ResourceManager.GetString("QuickSleepStormEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To Storm I 的本地化字符串。
        /// </summary>
        internal static string QuickSleepToStormI {
            get {
                return ResourceManager.GetString("QuickSleepToStormI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To Storm II 的本地化字符串。
        /// </summary>
        internal static string QuickSleepToStormII {
            get {
                return ResourceManager.GetString("QuickSleepToStormII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To {0} 的本地化字符串。
        /// </summary>
        internal static string QuickSleepToTime {
            get {
                return ResourceManager.GetString("QuickSleepToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Until Rainy 的本地化字符串。
        /// </summary>
        internal static string QuickSleepUntilRainy {
            get {
                return ResourceManager.GetString("QuickSleepUntilRainy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buildings that require this item: 的本地化字符串。
        /// </summary>
        internal static string RequirementsBuilding {
            get {
                return ResourceManager.GetString("RequirementsBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perks that require this item: 的本地化字符串。
        /// </summary>
        internal static string RequirementsPerk {
            get {
                return ResourceManager.GetString("RequirementsPerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hold Shift for details 的本地化字符串。
        /// </summary>
        internal static string RequirementsPressShift {
            get {
                return ResourceManager.GetString("RequirementsPressShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quests that require this item: 的本地化字符串。
        /// </summary>
        internal static string RequirementsQuestPrepare {
            get {
                return ResourceManager.GetString("RequirementsQuestPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quests that require submitting this item: 的本地化字符串。
        /// </summary>
        internal static string RequirementsQuestSubmit {
            get {
                return ResourceManager.GetString("RequirementsQuestSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quests that require using this item: 的本地化字符串。
        /// </summary>
        internal static string RequirementsQuestUse {
            get {
                return ResourceManager.GetString("RequirementsQuestUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total / required: 的本地化字符串。
        /// </summary>
        internal static string RequirementsTotal {
            get {
                return ResourceManager.GetString("RequirementsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shadow color 的本地化字符串。
        /// </summary>
        internal static string ShadowColor {
            get {
                return ResourceManager.GetString("ShadowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shadow width 的本地化字符串。
        /// </summary>
        internal static string ShadowWidth {
            get {
                return ResourceManager.GetString("ShadowWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show backpack count 的本地化字符串。
        /// </summary>
        internal static string ShowBackpackCount {
            get {
                return ResourceManager.GetString("ShowBackpackCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show fuse progress 的本地化字符串。
        /// </summary>
        internal static string ShowFuseProgress {
            get {
                return ResourceManager.GetString("ShowFuseProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outline ground items 的本地化字符串。
        /// </summary>
        internal static string ShowGroundItemOutline {
            get {
                return ResourceManager.GetString("ShowGroundItemOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outline loot containers 的本地化字符串。
        /// </summary>
        internal static string ShowLootboxOutline {
            get {
                return ResourceManager.GetString("ShowLootboxOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show names 的本地化字符串。
        /// </summary>
        internal static string ShowNames {
            get {
                return ResourceManager.GetString("ShowNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show storage count 的本地化字符串。
        /// </summary>
        internal static string ShowRepositoryCount {
            get {
                return ResourceManager.GetString("ShowRepositoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show smoke duration 的本地化字符串。
        /// </summary>
        internal static string ShowSmokeTimer {
            get {
                return ResourceManager.GetString("ShowSmokeTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start showing below 的本地化字符串。
        /// </summary>
        internal static string ShowThreshold {
            get {
                return ResourceManager.GetString("ShowThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smoke timer color 的本地化字符串。
        /// </summary>
        internal static string SmokeTimerColor {
            get {
                return ResourceManager.GetString("SmokeTimerColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fallback FMOD event path 的本地化字符串。
        /// </summary>
        internal static string SoundEventPath {
            get {
                return ResourceManager.GetString("SoundEventPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume 的本地化字符串。
        /// </summary>
        internal static string SoundVolume {
            get {
                return ResourceManager.GetString("SoundVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Star 的本地化字符串。
        /// </summary>
        internal static string Star {
            get {
                return ResourceManager.GetString("Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Carry 的本地化字符串。
        /// </summary>
        internal static string StorageCarry {
            get {
                return ResourceManager.GetString("StorageCarry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repo 的本地化字符串。
        /// </summary>
        internal static string StorageRepository {
            get {
                return ResourceManager.GetString("StorageRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text format 的本地化字符串。
        /// </summary>
        internal static string TextFormat {
            get {
                return ResourceManager.GetString("TextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is replaced with the target name 的本地化字符串。
        /// </summary>
        internal static string TextFormatTooltip {
            get {
                return ResourceManager.GetString("TextFormatTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dynamic 的本地化字符串。
        /// </summary>
        internal static string TrackingDynamic {
            get {
                return ResourceManager.GetString("TrackingDynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Static 的本地化字符串。
        /// </summary>
        internal static string TrackingStatic {
            get {
                return ResourceManager.GetString("TrackingStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use item quality colors 的本地化字符串。
        /// </summary>
        internal static string UseQualityColor {
            get {
                return ResourceManager.GetString("UseQualityColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning threshold 的本地化字符串。
        /// </summary>
        internal static string WarningThreshold {
            get {
                return ResourceManager.GetString("WarningThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start changing the crosshair color below this remaining magazine ratio 的本地化字符串。
        /// </summary>
        internal static string WarningThresholdTooltip {
            get {
                return ResourceManager.GetString("WarningThresholdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom 的本地化字符串。
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom in key 的本地化字符串。
        /// </summary>
        internal static string ZoomInKey {
            get {
                return ResourceManager.GetString("ZoomInKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom out key 的本地化字符串。
        /// </summary>
        internal static string ZoomOutKey {
            get {
                return ResourceManager.GetString("ZoomOutKey", resourceCulture);
            }
        }
    }
}
